version: '3.7'

services:
  app:
    container_name: file-explorer-fe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 4200:4200 
